settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: any-bot-website # unique identifier
    name: Any Bot Website
    description: 'This is the oficial Any Bot Website' # default=empty
    url: 'https://any-bot.tech/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: any-bot
    name: Any Bot
    description: 'Status about the Any Bot'
    url: 'https://any-bot.tech/bot-status'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: oxiservi
    name: Oxiservi
    url: 'https://oxiservi.com/'
    method: GET
    expectStatus: 200
    
  - id: mdcdev
    name: MDC Home Page
    url: 'https://mdcdev.me/'
    method: GET
    expectStatus: 200
    
  - id: mycommand
    name: My Command
    url: 'https://mycommand.xyz/'
    method: GET
    expectStatus: 200
